### ISSUE TITLE
No patches for stable?

### ISSUE THREAD

**Issue by nicholaschiasson** [openresty/no-pool-nginx#11]
Might I ask why it seems you only support mainline versions? I have test scenarios in which I use stable versions of nginx.

**Comment by agentzh** [comment]
This repo is mainly for OpenResty development so we only add patches for OpenResty's planned nginx core versions. If you need patches for other versions, you can create pull requests yourself basing on existing patches.

**Comment by nicholaschiasson** [comment]
Okay I understand. Thank you! 😄
